######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 10 20:31:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/include/calendar-backend
LIBS += -lcalendar_backend  

# Input
SOURCES += main.cpp
